### ISSUE TITLE
1.34 release ?

### ISSUE THREAD

**Issue by OdyX** [OpenPrinting/ippusbxd#16]
There are a lot if improvements on top of 1.33; care to release ?

**Comment by tillkamppeter** [comment]
OK, I will release soon.
But note that ippusbxd has important architectural deficiencies an it is recommended to use [ipp-usb](https://github.com/alexpevzner/ipp-usb/) instead. It is written n Go and therefore the executable is larger but this should not be a problem on modern systems. I highly recommend to use that one in Debian.
One of the deficiencies of ippusbxd, not the most important though, is that the DNS-SD advertising of ippusbxd is hard-coded and does not represent actual devices, especially cannot cope with whether the device has a scanner or not. @ordissimo has promised to fix this by asking the device on daemon startup (like it works in ipp-usb now) in February. Should I perhaps wait for this with a release?

**Comment by ThierryHFR** [comment]
Le 2020-01-31 17:49, Till Kamppeter a écrit :
> OK, I will release soon.
> But note that ippusbxd has important architectural deficiencies an it
> is recommended to use ipp-usb [1] instead. It is written n Go and
> therefore the executable is larger but this should not be a problem on
> modern systems. I highly recommend to use that one in Debian.
> One of the deficiencies of ippusbxd, not the most important though, is
> that the DNS-SD advertising of ippusbxd is hard-coded and does not
> represent actual devices, especially cannot cope with whether the
> device has a scanner or not. @Ordissimo [2] has promised to fix this
> by asking the device on daemon startup (like it works in ipp-usb now)
> in February. Should I perhaps wait for this with a release?
Hi @till.kamppeter,
I would push a patch very soon.
The idea of recovering the data in the capabilites file is excellent.
The DNS-SD interface will be dynamic and device specific.

**Comment by tillkamppeter** [comment]
@Ordissimo, any plans when you will post your Pull Request?

**Comment by ThierryHFR** [comment]
Hi @tillkamppeter,
I'll propose a fix by Monday.

**Comment by tillkamppeter** [comment]
@DavieV, @OdyX, please test the additions from @Ordissimo for the DNS-SD advertising of the device. Is this all OK for you? Then I will do the 1.34 release.

**Comment by tillkamppeter** [comment]
Done:
https://github.com/OpenPrinting/ippusbxd/releases/tag/1.34
Commit: 2b060a9
Thank you very much to everyone who has contributed!
