### ISSUE TITLE
Wrong paper size advertised for HP LaserJet MFP M28

### ISSUE THREAD

**Issue by alexpevzner** [OpenPrinting/ippusbxd#39]
This bug was actually found in the `ipp-usb`, but because `ippusbxd` borrows paper size detection code from there, I believe it is relevant to `ippusbxd` project too.

See https://github.com/OpenPrinting/ipp-usb/issues/6 for details.

**Comment by tillkamppeter** [comment]
@Ordissimo, could you have a look?

**Comment by ThierryHFR** [comment]
fix in https://github.com/OpenPrinting/ippusbxd/pull/41

**Comment by tillkamppeter** [comment]
Merged pull request #41. Thank you very much.
